- proto-gen-macos.sh
- src/features/manage-user/model/types.ts
- src/features/manage-user/model/use-create-user.ts
- src/features/manage-user/model/use-update-user.ts
- src/features/manage-user/ui/create-user-modal.tsx
- src/features/manage-user/ui/user-form.tsx
- src/features/test/test.tsx
- src/features/user-registry-filters/model/types.ts
- src/features/user-registry-filters/ui/user-registry-filters.tsx
- src/screens/user-registry-page/ui/user-registry-page.tsx
- src/shared/grpc/GrpcClientProvider.tsx
- src/shared/grpc/errorMiddleware.ts
- src/shared/grpc/grpc-error.ts
- src/shared/hooks/use-sort.ts
- src/shared/lib/create-filter-mapper.ts
- src/shared/stores/AuthStore.ts
- src/shared/ui/sort-th.tsx
- src/shared/utils/fetchClient.ts
---
PR составлен по задаче - DP-440
> feat: [DP-440] users crud

- app/[lang]/administration/page.tsx
- package.json
- src/entities/order/model/use-get-orders.ts
- src/entities/order/ui/order-row.tsx
- src/features/manage-methods/model/use-create-method.ts
- src/features/manage-order/model/use-create-order.ts
- src/features/manage-order/model/use-get-order.ts
- src/features/manage-order/model/use-update-order.ts
- src/features/manage-permissions/model/use-create-permission.ts
- src/features/manage-roles/model/use-create-role.ts
- src/features/order-filters/ui/orders-filters.tsx
- src/screens/administration-page/ui/administration-page.tsx
- src/screens/orders-page/ui/orders-page.tsx
> bug: [fix/hotfix-build] - hot fix

- public/dictionaries/en.json
- src/features/manage-tariff/model/types.ts
- src/features/manage-tariff/ui/tariff-form.tsx
- src/screens/tariffs-page/ui/tariffs-page.tsx
- src/shared/lib/decimal.ts
---
PR составлен по задаче - [DP-1238]
> bug: [DP-1238] - доработка тарифов

- app/[lang]/layout.tsx
> bug: [hotfix-table-ui] - add css in layout

- proto-gen-macos.sh
- public/dictionaries/en.json
- src/features/auth/model/types.ts
- src/features/auth/ui/login-by-email-form.tsx
- src/features/auth/ui/register-form.tsx
---
PR составлен по задаче - [DP-1226]
> feat: [DP-1226] - доработки аутентификации

- public/dictionaries/en.json
- src/features/auth/ui/reset-form.tsx
- src/shared/grpc/errorMiddleware.ts
---
PR составлен по задаче - [DP-1228]
> fix: [DP-1228] исправлены переводы

- middleware.ts
- src/features/auth/ui/auth-provider.tsx
- src/shared/lib/index.ts
- src/shared/lib/roels.ts
- src/shared/router.ts
- src/shared/stores/AuthStore.ts
- src/widgets/sidebar/ui/sidebar.tsx
---
PR составлен по задаче - [DP-1032]
> feat: [DP-1032] приватные роуты в зависимости от ролей

- src/features/manage-user/ui/user-form.tsx
---
PR составлен по задаче - [DP-1233]
> bug: [DP-1233] - fix label

- src/features/manage-invoices/ui/invoice-form.tsx
---
PR составлен по задаче - [DP-1501]
> feat: [DP-1501] автозаполнение полей счета

- middleware.ts
- src/entities/user/index.ts
- src/features/auth/model/types.ts
- src/features/auth/model/use-login-by-email.ts
- src/features/auth/ui/auth-provider.tsx
- src/features/auth/ui/update-password-modal.tsx
- src/screens/welcome-landing-page/welcome-landing-page.tsx
- src/shared/lib/get-current-user.ts
- src/shared/lib/index.ts
- src/widgets/sidebar/ui/sidebar.tsx
---
PR составлен по задаче - [DP-1647]
> fix: [DP-1647] исправлен баг при логине

- public/dictionaries/en.json
- src/features/user-registry-filters/ui/user-registry-filters.tsx
- src/screens/user-registry-page/ui/user-registry-page.tsx
- src/shared/lib/create-filter-mapper.ts
---
PR составлен по задаче - [DP-1622]
> feat: [DP-1622] - users filters

- proto/api_tips_balance/v1/api_tips_balance.proto
- public/dictionaries/en.json
- src/features/balance/deps.ts
- src/features/balance/index.ts
- src/features/balance/ui/update-user-balance-modal.tsx
- src/features/balance/ui/use-update-user-balance-modal.tsx
- src/features/balance/ui/user-balance-form.tsx
- src/screens/histories-page/providers.tsx
- src/screens/histories-page/ui/histories-page.tsx
- src/widgets/histories-table/ui/histories-table.tsx
---
PR составлен по задаче - [DP-1600]
> feat: [DP-1600] - update histories table

- app/[lang]/my-orders/page.tsx
- proto/api_tips_order/v1/api_tips_order.proto
- public/dictionaries/en.json
- src/entities/order/index.ts
- src/entities/order/model/use-get-orders-for-client.ts
- src/features/manage-invoices/ui/invoice-form.tsx
- src/features/manage-order/ui/order-form.tsx
- src/features/manage-user-orders/deps.ts
- src/features/manage-user-orders/index.ts
- src/features/manage-user-orders/model/types.ts
- src/features/manage-user-orders/model/use-add-order.ts
- src/features/manage-user-orders/model/use-add-user-order.ts
- src/features/manage-user-orders/model/use-get-order.ts
- src/features/manage-user-orders/ui/add-user-order-modal.tsx
- src/features/manage-user-orders/ui/use-add-user-order-modal.tsx
- src/features/manage-user-orders/ui/user-order-form.tsx
- src/features/order-filters/ui/orders-filters.tsx
- src/screens/user-orders-page/index.ts
- src/screens/user-orders-page/providers.tsx
- src/screens/user-orders-page/ui/user-orders-page.tsx
- src/shared/lib/query-keys.ts
- src/shared/router.ts
- src/widgets/sidebar/ui/sidebar.tsx
---
PR составлен по задаче - [DP-1503]
> feat: [DP-1503] клиентская часть заказов

- package.json
- setupTests.ts
- src/shared/ui/button.test.tsx
- vitest.config.mts
- yarn.lock
---
PR составлен по задаче - [DP-1648]
> feat: [DP-1648] - setup tests

- src/features/manage-invoices/ui/update-invoice-form.tsx
---
PR составлен по задаче - [DP-1681]
> bug: [DP-1681] - hide unspecified option in invoice update form

- src/screens/dashboard-page/ui/dashboard-page.tsx
---
PR составлен по задаче - [DP-1709]
> feat: [DP-1709] - update default date range

- public/dictionaries/en.json
- src/widgets/sidebar/ui/sidebar.tsx
---
PR составлен по задаче - [DP-1708]
> feat: [DP-1708] - rename sidebar links

- proto/api_tips_access/v1/api_tips_access.proto
- public/dictionaries/en.json
- src/features/manage-user/index.ts
- src/features/manage-user/model/types.ts
- src/features/manage-user/model/use-update-profile.ts
- src/features/manage-user/ui/update-user-profile-modal.tsx
- src/features/manage-user/ui/use-update-user-profile-modal.tsx
- src/screens/profile-page/ui/profile-page.tsx
---
PR составлен по задаче - [DP-1689]
> feat: [DP-1689] - update account details

- .eslintrc.json
- middleware.ts
- package.json
- proto/api_tips_access/v1/api_tips_access.proto
- public/dictionaries/en.json
- setupTests.ts
- src/entities/histrory/model/use-get-user-histories.ts
- src/entities/user/index.ts
- src/entities/user/model/use-get-detailed-user.ts
- src/entities/user/testing/factories.ts
- src/features/auth/ui/forgot-password-form.tsx
- src/features/manage-invoices/ui/update-invoice-form.tsx
- src/features/manage-user/index.ts
- src/features/manage-user/model/use-update-token-tips/update-user-tips-token.test.tsx
- src/features/manage-user/model/use-update-token-tips/use-update-token-tips.ts
- src/features/manage-user/ui/update-user-tips-token/update-user-tips-token.test.tsx
- src/features/manage-user/ui/update-user-tips-token/update-user-tips-token.tsx
- src/screens/dashboard-page/ui/dashboard-page.tsx
- src/screens/user-orders-page/ui/user-orders-page.tsx
- src/screens/welcome-landing-page/welcome-landing-page.tsx
- src/shared/hooks/index.ts
- src/shared/hooks/use-timer.ts
- src/shared/lib/query-keys.ts
- src/shared/testing/factories/response.factories.ts
- src/shared/testing/index.ts
- src/shared/testing/renderWithProviders.tsx
- src/shared/testing/translations.ts
- src/widgets/sidebar/ui/sidebar.tsx
- yarn.lock
---
PR составлен по задаче - [DP-1607]
> feat: [DP-1607] добавлено отображение токена с возможностью обновления

- proto/api_tips_balance/v1/api_tips_balance.proto
- src/entities/histrory/model/use-get-histories.ts
- src/features/history-filters/ui/history-filters.tsx
- src/screens/histories-page/ui/histories-page.tsx
---
PR составлен по задаче - [DP-1690]
> feat: [DP-1690] - filter history by user id

- src/features/manage-user-orders/ui/add-user-order-modal.tsx
- src/features/manage-user-orders/ui/use-add-user-order-modal.tsx
- src/features/manage-user-orders/ui/user-order-form.tsx
- src/screens/dashboard-page/ui/dashboard-page.tsx
- src/screens/orders-page/ui/orders-page.tsx
- src/screens/user-orders-page/ui/user-orders-page.tsx
- src/screens/welcome-landing-page/welcome-landing-page.tsx
- src/shared/ui/button.tsx
---
PR составлен по задаче - [DP-1719]
> feat: [DP-1719] - redirect to my orders page

- README.md
---
PR составлен по задаче - [DP-1773]
> feat: [DP-1773] - upd readme file
